<a href="https://colab.research.google.com/github/vithal-4u/Machine_Learning/blob/master/numpyArrayCreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
from numpy import pi

print('@@*** int array ***@@')
a = np.array([2, 3, 4])
print(a)
print(a.dtype)

print('*** float array ***')
b = np.array([2.1, 3.2, 4.0])
print(b)
print(b.dtype)

print('*** 2D array ***')
# 2D Array
x = np.array([[1.5, 2, 3], [4, 5, 6]])
print(x)
print(x.dtype)

print('*** complex ***')
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

print('*** zeros ***')
print(np.zeros((3, 4)))

print('*** ones ***')
print(np.ones((2, 3, 4), dtype=np.int16))

print('*** eye ***')
print(np.eye(3))

print('*** empty ***')
print(np.empty((2, 3)))

print('*** arange ***')
d = np.arange(0, 2.5, 0.3)
print(d)

print('*** reshape ***')
x = d.reshape(3, 3)
print(x)

print('@@@*** lin space ***')
e = np.linspace(0, 2, 9)
print(e)
print('')

f = np.linspace(0, 2*pi, 90)
print(f)

print('@@@*** random number ***')
h = np.random.random((3, 4))
print(h)
print('')

k = np.random.randint(1, 25, size=(3, 4))
print(k)
print('')

l = np.random.randint(1, 25, (3, 4))
print(l)

@@*** int array ***@@
[2 3 4]
int64
*** float array ***
[2.1 3.2 4. ]
float64
*** 2D array ***
[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64
*** complex ***
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
*** zeros ***
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*** ones ***
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
*** eye ***
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*** empty ***
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
*** arange ***
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
*** reshape ***
[[0.  0.3 0.6]
 [0.9 1.2 1.5]
 [1.8 2.1 2.4]]
@@@*** lin space ***
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

[0.         0.07059759 0.14119518 0.21179276 0.28239035 0.35298794
 0.42358553 0.49418311 0.5647807  0.63537829 0.70597588 0.77657346
 0.84717105 0.91776864 0.98836623 1.05896382 1.1295614  1.20015899
 1.27075658 1.34135417 1.41195175 1.48254934 1.55314693 1.62374452
 1.69434211 1.76493969 1.83553728 1.90613487 1.9