<a href="https://colab.research.google.com/github/vithal-4u/Machine_Learning/blob/master/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# NumPy’s main object is the homogeneous multidimensional array
print('*** Create and print an array ***')
a = np.arange(16).reshape(4, 4)
print(a)

print('*** Shape of the array ***')
print(a.shape)

print('*** Dimension or rank of array ***')
print(a.ndim)       # rank

print('*** data type of array ***')
print(a.dtype.name)

print('*** size of array items ***')
print(a.itemsize)

print('*** size of array ***')
print(a.size)

print('*** array type***')
print(type(a))

print('*** Create an array explicitly providing values ***')
b = np.array([6, 7, 8])
print(b)


*** Create and print an array ***
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
*** Shape of the array ***
(4, 4)
*** Dimension or rank of array ***
2
*** data type of array ***
int64
*** size of array items ***
8
*** size of array ***
16
*** array type***
<class 'numpy.ndarray'>
*** Create an array explicitly providing values ***
[6 7 8]
