<a href="https://colab.research.google.com/github/vithal-4u/Machine_Learning/blob/master/numpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

print('@@@@ *** array operations ***@@@@')
a = np.array([20, 30, 40, 50])
print("a",a)
b = np.arange(4)
print("b",b)

print('*** subtraction ***')
c = a-b
print("c",c)

print('*** exponentiation ***')
print("b",b)
print("b**2",b**2)

print('*** integer multiplication and trigonometric operation ***')
print("np.sin(a)---",np.sin(a))
print("10 * np.sin(a)---",10 * np.sin(a))

print('*** Comparison (element-wise) with a number ***')
print("a < 35---",a < 35)

print('@@@@ *** Array Products ***@@@@')
A = np.array([[2, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print('*** element-wise product ***')
print("A ---",A)
print("B ---",B)
print(A*B)           # element-wise product

print('*** matrix product ***')
print("A.dot(B) ---",A.dot(B))       # matrix product

print('*** matrix product (other approach)***')
print(np.dot(A, B))   # another matrix product

print('@@@@ *** sum, max, min ***@@@@')
x = np.random.random((4, 5))
print("Random ---",x)

@@@@ *** array operations ***@@@@
a [20 30 40 50]
b [0 1 2 3]
*** subtraction ***
c [20 29 38 47]
*** exponentiation ***
b [0 1 2 3]
b**2 [0 1 4 9]
*** integer multiplication and trigonometric operation ***
np.sin(a)--- [ 0.91294525 -0.98803162  0.74511316 -0.26237485]
10 * np.sin(a)--- [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
*** Comparison (element-wise) with a number ***
a < 35--- [ True  True False False]
@@@@ *** Array Products ***@@@@
*** element-wise product ***
A --- [[2 1]
 [0 1]]
B --- [[2 0]
 [3 4]]
[[4 0]
 [0 4]]
*** matrix product ***
A.dot(B) --- [[7 4]
 [3 4]]
*** matrix product (other approach)***
[[7 4]
 [3 4]]
@@@@ *** sum, max, min ***@@@@
Random --- [[0.58441551 0.52744741 0.73214688 0.79036097 0.86135218]
 [0.79626893 0.93950321 0.95672497 0.45887608 0.26647666]
 [0.29760314 0.74540848 0.12569745 0.12748854 0.95429314]
 [0.99316943 0.12624198 0.36472981 0.39450831 0.65244614]]


In [48]:
print('*** ....after reshape ***')
print(x.reshape(-1, 4))

print('*** sum ***')
print(x.sum())
print('*** max ***')
print(x.max())
print('*** min ***')
print(x.min())

print('@@@@ *** unary operations ***@@@@')
y = np.arange(12).reshape(4, -1)
print(y)

print('*** sum of each column ***')
print(y.sum(axis=0))        # sum of each column
print('*** min of each row ***')
print(y.min(axis=1))   

print('*** cumulative sum along each row ***')
print(y.cumsum(axis=1))     # cumulative sum along each row

print('@@@*** Universal Functions ***@@@')
print('*** exponentiation ***')
print(np.exp(y))

print('*** square root ***')
print(np.sqrt(y))
print('*** expression ***')
print(np.add(np.exp(y), 10*y))

*** ....after reshape ***
[[0.58441551 0.52744741 0.73214688 0.79036097]
 [0.86135218 0.79626893 0.93950321 0.95672497]
 [0.45887608 0.26647666 0.29760314 0.74540848]
 [0.12569745 0.12748854 0.95429314 0.99316943]
 [0.12624198 0.36472981 0.39450831 0.65244614]]
*** sum ***
11.69515919878398
*** max ***
0.993169431721049
*** min ***
0.12569745492056994
@@@@ *** unary operations ***@@@@
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
*** sum of each column ***
[18 22 26]
*** min of each row ***
[0 3 6 9]
*** cumulative sum along each row ***
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]
@@@*** Universal Functions ***@@@
*** exponentiation ***
[[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04]]
*** square root ***
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.

In [49]:
print('@@@@*** operation along the specified axis of an array ***@@@@')
z = np.array([[25, 12, 29, 7],
              [23, 14, 8, 43],
              [24, 19, 47, 40]])
print(z)
print(z[0]-z[1])
print(z[0]+z[1])
print(z[0]*z[1])
print(z.astype('float')[0]/z[1])

@@@@*** operation along the specified axis of an array ***@@@@
[[25 12 29  7]
 [23 14  8 43]
 [24 19 47 40]]
[  2  -2  21 -36]
[48 26 37 50]
[575 168 232 301]
[1.08695652 0.85714286 3.625      0.1627907 ]
