<a href="https://colab.research.google.com/github/vithal-4u/Machine_Learning/blob/master/numpyIndexing%26Iteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

# 1D array
print('@@@@ *** 1D arrays ***')
a = np.arange(10)**3
print(a)
print('*** a[2:5] ***')
print(a[2:5])

print('*** modify few elements in array ***')
a[0:8:3] = 500
print(a)

print('*** iterate a ***')
for i in a:
    print(i**(1/3))
print('')

# 2D Array
print('@@@@ *** 2D arrays ***')


def f(x, y):
    return 10*x+y

b = np.fromfunction(f, (4, 3), dtype=int)
print(b)

@@@@ *** 1D arrays ***
[  0   1   8  27  64 125 216 343 512 729]
*** a[2:5] ***
[ 8 27 64]
*** modify few elements in array ***
[500   1   8 500  64 125 500 343 512 729]
*** iterate a ***
7.937005259840997
1.0
2.0
7.937005259840997
3.9999999999999996
4.999999999999999
7.937005259840997
6.999999999999999
7.999999999999999
8.999999999999998

@@@@ *** 2D arrays ***
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [24]:
print('*** slicing ***')
print(b[3, 1])
print(b[:, 0])
print(b[:, -1])

print('*** iterate ***')
# Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)
    
for element in b.flat:
    print(element)

*** slicing ***
31
[ 0 10 20 30]
[ 2 12 22 32]
*** iterate ***
[0 1 2]
[10 11 12]
[20 21 22]
[30 31 32]
0
1
2
10
11
12
20
21
22
30
31
32


In [26]:
# 3D array
print('@@@@ *** 3D arrays ***')
c = np.array([[[0,  1,  2],               # a 3D array (two stacked 2D arrays)
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

print(c)

print('*** shape of 3D array')
print(c.shape)
print('*** slicing')
print(c[1, ...])
print('*** slicing- another approach')
print(c[1, :, :])

@@@@ *** 3D arrays ***
[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
*** shape of 3D array
(2, 2, 3)
*** slicing
[[100 101 102]
 [110 112 113]]
*** slicing- another approach
[[100 101 102]
 [110 112 113]]
