<a href="https://colab.research.google.com/github/vithal-4u/Machine_Learning/blob/master/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# NumPy’s main object is the homogeneous multidimensional array
print('*** Create and print an array ***')
a = np.arange(16).reshape(4, 4)
print(a)

*** Create and print an array ***
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
