<a href="https://colab.research.google.com/github/vithal-4u/Machine_Learning/blob/master/numpyShapeManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
# Initialize a seed so that we get the same results-
# -all the time and we can keep a track

np.random.seed(50)

print('**** a ****')
a = np.random.random((3, 4))
print(a)

print('**** floor(10*a) ****')
b = np.floor(10*a)
print(b)

print('**** b.ravel() ****')
print(b.ravel())

print('**** b.shape = (6, 2) ****')
b.shape = (6, 2)
print(b)

print('**** b.T ****')
print(b.T)          # Transpose

print('**** b.reshape(3, -1) ****')
print(b.reshape(3, -1))

**** a ****
[[0.49460165 0.2280831  0.25547392 0.39632991]
 [0.3773151  0.99657423 0.4081972  0.77189399]
 [0.76053669 0.31000935 0.3465412  0.35176482]]
**** floor(10*a) ****
[[4. 2. 2. 3.]
 [3. 9. 4. 7.]
 [7. 3. 3. 3.]]
**** b.ravel() ****
[4. 2. 2. 3. 3. 9. 4. 7. 7. 3. 3. 3.]
**** b.shape = (6, 2) ****
[[4. 2.]
 [2. 3.]
 [3. 9.]
 [4. 7.]
 [7. 3.]
 [3. 3.]]
**** b.T ****
[[4. 2. 3. 4. 7. 3.]
 [2. 3. 9. 7. 3. 3.]]
**** b.reshape(3, -1) ****
[[4. 2. 2. 3.]
 [3. 9. 4. 7.]
 [7. 3. 3. 3.]]
